baseURL: https://rahulgadre.com
title: "Rahul Gadre"
author: "Rahul Gadre"
permalink: /:title/
paginate: 6
theme: charlolamode

menu:
    main:
    
       # - name: Resume
       #   url: https://rahulgadre.com/resume/
       #   external: true # set true if you using external link, see below
       #   weight: 35
        - name: About
          url: /about/
          weight: 30
        - name: Blog
          url: /blog/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   
params:
    author: Rahul Gadre
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Rahul Gadre
        description: |

          Hello, I am Rahul - A Cloud Engineer and Cloud Advocate. 
        
        imageUrl: "/images/my_new_pic.jpeg"
        imageTitle: Rahul Gadre
        # imageWidth: 120
        # imageHeight: 120
        buttons:
         - name: Resume
           url: https://rahulgadre.com/resume/
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/rggadre"
        - name: github
          url: "https://github.com/rahulgadre"
        - name: linkedin
          url: "https://www.linkedin.com/in/rahulgadre/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/my_new_pic.jpeg"
          favicon32x32: "/images/my_new_pic.jpeg"
          apple_touch_icon: "/images/my_new_pic.jpeg"
          safari_pinned_tab: "/images/my_new_pic.jpeg"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
